### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by larrybg** [Nosinden/LetFap.bundle#1]
doesn't load or play anything right now - plex or website

**Comment by Nosinden** [comment]
Thanks for the heads up.  Seems the website is having some issues, so I'll update the channel to reflect when videos go offline.

**Comment by Nosinden** [comment]
Fix in [v1.0.4](https://github.com/Nosinden/LetFap.bundle/tree/v1.0.4), will now display when a video is offline.

**Comment by larrybg** [comment]
Thanks, for the quick fix! The thing is - all videos are offline. A week ago I could play some of them. Is there any explanation? Is this plugin free, or require a payment (since it's coming from website where membership is required)?

**Comment by Nosinden** [comment]
> Thanks, for the quick fix!

You're welcome.

> Is this plugin free, or require a payment (since it's coming from website where membership is required)?

This channel pulls its info from http://letfap.com site, which re-host the x-art.com videos for free using Google Servers.  The letfap site is free.

> The thing is - all videos are offline. A week ago I could play some of them. Is there any explanation? 

Many sites like this are in violation of Google's terms of service, and as such their videos get removed ever so often.  You'll have to wait for the letfap site to re-upload the videos.  I did notice many of the recent videos are offline, but most of the older content is still available.

**Comment by terster** [comment]
On Plex for Roku, thumbnails were updated 8 months ago by notvinny however, videos remain offline.  Is this something that can be fixed? The 3 different JAV channels are also offline.  Just curious if you can help.  Thnx.
